### ISSUE TITLE
Any plan to continue this project?

### ISSUE THREAD

**Issue by zhangwei983** [willnationsdev/godot-source-walkthrough#2]
Thanks.

**Comment by willnationsdev** [comment]
I certainly would like to someday, but that's the most I can say for now. There are many pressing needs at my day job that I've been putting my extra time & effort into, but when things slow down, you may see some more activity in this project as I try to clean up / finish the basic "GDScript to C++" content and then prepare and present actual videos covering the Godot Engine source code. It would be ideal if I could do so before Godot 4.0 is fully released since creating such tutorial resources might then make it easier / more accessible for the community to see themselves getting involved in Godot Engine development (and accelerate things a bit).

I appreciate your continued interest in the project though! Thanks.

Edit: I'm closing the issue for now - for stats' sake - but you are free to continue with questions if you'd like to.
